language: csharp
sudo: false

install:
    - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
    - dnvm install latest -r mono
    - dnu restore

script:
    - dnx LimeBean.Tests xunit.runner.dnx -notrait db=mssql