language: csharp
sudo: required
mono: nightly

env:
  global:
    - LIME_TEST_MARIA_HOST=127.0.0.1
    - LIME_TEST_MARIA_USER=root
    - LIME_TEST_MARIA_PWD=""
    - LIME_DNX_VERSION=1.0.0-beta6
    - LIME_XUNIT_CONSOLE_VERSION=2.1.0-beta4-build3050

install:
  - ./travis-update-sqlite.sh

  # Install DNX
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh && source ~/.dnx/dnvm/dnvm.sh
  - dnvm install $LIME_DNX_VERSION -r mono

  # Install NuGet
  - wget https://nuget.org/nuget.exe

  # Restore packages
  - dnu restore LimeBean.Dnx
  - mono ./nuget.exe restore LimeBean.sln -verbosity detailed

script:
  # Build 
  - xbuild LimeBean.sln /nologo /v:q /t:Rebuild /p:SQLiteMode=MONO
  - dnu build LimeBean.Dnx/LimeBean --quiet
  - dnu build LimeBean.Dnx/LimeBean.Tests --quiet

  # Test
  - mono ./packages/xunit.runner.console.$LIME_XUNIT_CONSOLE_VERSION/tools/xunit.console.exe ./bin/LimeBean.Tests.dll -noappdomain -notrait db=mssql
  - dnx LimeBean.Dnx/LimeBean.Tests xunit.runner.dnx -notrait db=mssql