version: '{build}'

clone_depth: 50

environment:
  LIME_TEST_MARIA_PWD: Password12!
  LIME_TEST_PGSQL_PWD: Password12!
  LIME_TEST_MSSQL_NAME: (local)\SQL2008R2SP2
  LIME_DNX_VERSION: 1.0.0-beta7
  LIME_XUNIT_CONSOLE: packages\xunit.runner.console.2.1.0-rc1-build3124\tools\xunit.console.exe
  LIME_OPENCOVER_CONSOLE: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe
  LIME_COVERALLS: packages\coveralls.io.1.3.4\tools\coveralls.net.exe
  COVERALLS_REPO_TOKEN:
    secure: SMTYtN67tLVTDY4+OmEUtFeI1Iz+h99vn3gPynUDWrgtQU6rerpubVNmt3KNQw7+

cache:
  - packages
  - '%USERPROFILE%\.dnx\runtimes'
  - '%USERPROFILE%\.dnx\packages'

services:
  - mssql2008r2sp2
  - mysql56
  - postgresql

before_build:
  # Install DNX
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))
  - dnvm install %LIME_DNX_VERSION% -r coreclr
  - dnvm install %LIME_DNX_VERSION% -r clr

  # Restore packages
  - dnu restore LimeBean.Dnx --quiet
  - appveyor DownloadFile https://nuget.org/nuget.exe
  - nuget restore LimeBean.sln
  - nuget restore LimeBean.Xamarin\LimeBean.Xamarin.sln

build_script:
  - msbuild LimeBean.sln /v:m
  - msbuild LimeBean.Xamarin\LimeBean.Xamarin.sln /v:m
  - dnu build LimeBean.Dnx\LimeBean --quiet
  - dnu build LimeBean.Dnx\LimeBean.Tests --quiet

test_script:
  # .NET
  - '%LIME_OPENCOVER_CONSOLE% -register:user -target:%LIME_XUNIT_CONSOLE% -targetargs:"bin\LimeBean.Tests.dll -noshadow -appveyor" -filter:"+[LimeBean]*" -output:opencover.xml'

  # Copy SQLite binaries for DNX
  - xcopy /Y /I /S System.Data.SQLite\sqlite*.dll LimeBean.Dnx\LimeBean.Tests

  # DNXCore
  - dnvm use %LIME_DNX_VERSION% -r coreclr
  - dnx -p LimeBean.Dnx/LimeBean.Tests xunit.runner.dnx

  # DNX
  - dnvm use %LIME_DNX_VERSION% -r clr
  - dnx -p LimeBean.Dnx/LimeBean.Tests xunit.runner.dnx

on_success:
  - '%LIME_COVERALLS% --opencover opencover.xml'