version: '{build}'

clone_depth: 1

environment:
  LIME_TEST_MARIA_PWD: Password12!
  LIME_TEST_MSSQL_NAME: (local)\SQL2008R2SP2
  LIME_DNX_VERSION: 1.0.0-beta6

cache:
  - packages
  - '%USERPROFILE%\.dnx\runtimes'
  - '%USERPROFILE%\.dnx\packages'

services:
  - mssql2008r2sp2
  - mysql56

before_build:
  # Install DNX
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))
  - dnvm install %LIME_DNX_VERSION% -r coreclr
  - dnvm install %LIME_DNX_VERSION% -r clr

  # Restore packages
  - dnu restore LimeBean.Dnx --quiet
  - appveyor DownloadFile https://nuget.org/nuget.exe
  - nuget restore LimeBean.sln
  - nuget restore LimeBean.Xamarin\LimeBean.Xamarin.sln

build_script:
  - msbuild LimeBean.sln /v:m
  - msbuild LimeBean.Xamarin\LimeBean.Xamarin.sln /v:m
  - dnu build LimeBean.Dnx\LimeBean --quiet
  - dnu build LimeBean.Dnx\LimeBean.Tests --quiet

test_script:
  # .NET
  - '%xunit20%\xunit.console bin\LimeBean.Tests.dll -appveyor'

  # Copy SQLite binaries for DNX
  - xcopy /Y /I /S System.Data.SQLite\sqlite*.dll LimeBean.Dnx\LimeBean.Tests

  # DNXCore
  - dnvm use %LIME_DNX_VERSION% -r coreclr
  - dnx LimeBean.Dnx\LimeBean.Tests xunit.runner.dnx

  # DNX
  - dnvm use %LIME_DNX_VERSION% -r clr
  - dnx LimeBean.Dnx\LimeBean.Tests xunit.runner.dnx