version: '{build}'

environment:
    LIME_TEST_MARIA_PWD: Password12!
    LIME_TEST_MSSQL_NAME: (local)\SQL2008R2SP2

services:
    - mssql2008r2sp2
    - mysql56

before_build:
    - nuget restore LimeBean.sln -verbosity detailed

build:
  project: LimeBean.sln
  verbosity: minimal